# config.py
WINDOW_TITLE = "Automated Radio Frequency Identification System"
X_OFFSET = 0
Y_OFFSET = 0
WINDOW_HEIGHT = 900
WINDOW_WIDTH = 1600
SIDEBAR_COLOR = "#2c3e50"
BUTTON_COLOR = "#34495e"
APP_BACKGROUND_COLOR = '121212'
# APP_ICON=qta.icon('mdi.signal-5g')

# FIGURE REFRESH RATE
FIGURE_REFRESH_RATE = 200  # in milliseconds
PROBABILITY_REFRESH_RATE = 1000  # in milliseconds

# CHART COLORS #F9C74F, #FF6F91, #A2C2E0, and #6A82FB
CONSTELLATION_PLOT_COLOR = '#F9C74F'
FREQUENCY_DOMAIN_PLOT_COLOR = '#FF6F91'
TIME_DOMAIN_PLOT_COLOR = '#A2C2E0'
WATERFALL_PLOT_COLOR = '#ff6f91'
PROBABILITY_BAR_COLOR = '#6A82FB'
MODEL_PATH = "./models/combined_model.onnx"

VARS = {
    "SAMPLE_RATE": 1.024e6,
    "FFT_SIZE": 1024,
    "NUM_ROWS": 100,
    "CENTER_FREQUENCY": 95.6e6,
    "GAIN": 10,
    "BANDWIDTH": 1e6,
}
